chat_app/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('rooms/', include('room.urls', namespace='room')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from .views import frontpage, signuppage, loginpage, logout_user

app_name = 'core'

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('signup/', signuppage, name='signup'),
    path('login/', loginpage, name='login'),
    path('logout/', logout_user, name='logout'),
]

room/urls.py
from django.urls import path
from .views import rooms, create_room, chat_room



app_name = 'room'

urlpatterns = [
    path('', rooms, name='rooms'),
    path('create-room/', create_room, name='create-room'),
    path('<str:slug>/', chat_room, name='chat-room'),
]

core/models.py
from django.db import models


# Create your models here.

room/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify 

# Create your models here.

class ChatRoom(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128,unique=True)

    def save(self, *args, **kwargs):
        # Generate slug automatically before saving (your custom logic)
        self.slug = slugify(self.name)

        # Call the parent class's save method to execute its core functionality
        super().save(*args, **kwargs)



class Message(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    room = models.ForeignKey(to=ChatRoom, on_delete=models.CASCADE)
    content = models.TextField(max_length=512)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.content} [{self.timestamp}]'

core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupUser(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    pass

room/forms.py
from django import forms
from .models import ChatRoom

class RoomForm(forms.ModelForm):
    class Meta:
        model = ChatRoom
        fields = ['name']

core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import SignupUser, LoginForm
from django.contrib.auth import login, authenticate, logout

# Create your views here.

def frontpage(request):
    return render(request, 'core/landing_page.html')

def signuppage(request):
    if request.method == 'POST':
        form = SignupUser(request.POST)
        if form.is_valid():
            user = form.save()
            print(user)
            return redirect(reverse('core:frontpage'))
    
    form = SignupUser()
    return render(request, 'core/signup_page.html', {'form': form})

def loginpage(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('core:frontpage'))
    else: 
        form = LoginForm()

        return render(request, 'core/login_page.html', {'form': form})

def logout_user(request):
    logout(request)
    return redirect(reverse('core:frontpage'))

room/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import RoomForm
from .models import ChatRoom, Message
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def rooms(request):
    rooms = ChatRoom.objects.all()
    return render(request, 'room/chat_rooms.html', {'rooms': rooms})

@login_required
def create_room(request):
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('room:rooms'))
    else:
        form = RoomForm()

    context = {'form': form}
    return render(request, 'room/create_room.html', context)

@login_required
def chat_room(request, slug):
    room = ChatRoom.objects.filter(slug=slug).first()
    # print("printing roomname: ", slug)
    # print(room.slug)
    logged_in_user = request.user
    username = logged_in_user.username

    # now also retrieving all stored messages of that room 
    messages = Message.objects.filter(room=room)

    # retrieving recent 30 messages only 

    messages = messages.order_by('-timestamp')[:30][::-1]


    context = {
        'username': username,
        'room': room,
        'messages': messages,
    }

    return render(request, "room/chat_room.html", context)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChatApp</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <style>
        .chat-messages{
            height: 350px;
            overflow-y: auto;
        }
    </style>
</head>
<body class="bg-yellow-100 mx-5 my-2">
    <nav class="flex justify-between items-center bg-yellow-200 px-5 py-5 rounded-md">
        <div class="items-center text-white font-bold hover:text-yellow-800">
            <a href="{% url 'room:rooms' %}">View Rooms </a>
        </div>
        <div class="text-white font-bold">
            <a class="mx-auto" href="{% url 'core:frontpage' %}">Chat App</a>
        </div>
        {% if user.is_authenticated %}
        <div class="items-center text-white">
            <span class="px-3 py-3 font-bold">Welcome, {{user.username}} !</span>
            <a href="{% url 'core:logout' %}" class="bg-yellow-400 rounded-lg hover:bg-yellow-600 px-3 py-3">Log Out</a>
        </div>
        {% else %}
        <div class="items-center text-white">
            <a href="{% url 'core:login' %}" class="px-3 py-3">Login</a>
            <a href="{% url 'core:signup' %}" class="bg-yellow-400 rounded-lg hover:bg-yellow-600 px-3 py-3">Sign Up</a>
        </div>
        {% endif %}
    </nav>

    <div class="flex justify-center items-center my-10">
        <div class="w-3/5 text-center"> 
            {% block content %}
          
        {% endblock content %}
        </div>
      </div>


      
      
    </body>
    {% block script %}
    {% endblock script %}
</html>

core/templates/core/landing_page.html
{% extends "core/base.html" %}

{% block content %}
<h1 class="text-yellow-800 text-4xl font-bold">
    Welcome To Chat App
</h1>
{% endblock %}

core/templates/core/login_page.html
{% extends 'core/base.html' %}

{% block content %}
<div>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    

</div>
{% endblock content %}

core/templates/core/signup_page.html
{% extends "core/base.html" %}

{% block content %}
<div>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
    

</div>
{% endblock content %}

room/templates/room/chat_room.html
{% extends "core/base.html" %}

{% block content %}

    <!-- display messages here -->

    <div class="mb-5">
        <h1 class="text-3xl text-white font-bold">Chat Room: {{ room.name }}</h1>
    </div>
    
    <!-- <div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
        <div class="chat-messages space-y-3" id="show-messages">
            {% for message in messages %}<b>{{ message.user.username }}</b>: {{ message.content }}<br>{% endfor %}
        </div>
    </div> -->
<div class="w-1/2 bg-yellow-200 mx-auto p-4 rounded-xl">
    <div id="show-messages" class="chat-messages items-center justify-center ml-4 text-center">
        {% for message in messages %}
        <div class="flex mt-2">
            <p class="text-sm font-semibold mr-2 mt-2">{{ message.user.username }} : </p>
            <p class="bg-white rounded-xl p-2">{{ message.content }}</p>
            <!-- <p class="bg-white rounded-xl p-2">{{ message.content }}</p> -->
        </div>
        {% endfor %}
    </div>
    
    <!-- <div id="show-messages">
        {% for message in messages %}

        <p class="my-2 mx-2 bg-white rounded-xl">{{message.user.username}} : {{message.content}}</p>

        {% endfor %}

    </div> -->
    <!-- <p class="my-2 mx-2 bg-white rounded-xl"></p> -->
    <form method="post" action="." class="mt-2">
        {% csrf_token %}
        <input type="text" id="chat-message">
        <button type="submit" id="send-button">Send</button>
    </form>
    {{ room.slug|json_script:"json-roomname" }}
    {{ username|json_script:"json-username" }}

</div>
{% endblock content %}



{% block script %}
  <script >
    console.log("hello script is running...");

    const userNameElement = document.getElementById("json-username");
    const roomNameElement = document.getElementById("json-roomname");

    
    
    if (userNameElement && roomNameElement) {
        const userName = JSON.parse(userNameElement.textContent);
        const roomName = JSON.parse(roomNameElement.textContent);

        console.log("room name ", roomName);
        const ws_addr = "ws://"
            + window.location.host
            + '/ws/' + 'rooms/'
            + roomName;
        // const ws_addr = "ws://"
        //     + '127.0.0.1:8001'
        //     + '/ws/' + 'rooms/'
        //     + roomName;

        console.log(ws_addr);
        
        const ws = new WebSocket(
            ws_addr
        );

        // Event handler for successful connection
        ws.onopen = function(event) {
            console.log('WebSocket connection established.');
        };

        const messages = document.getElementById('show-messages');

        // function addMessage(messageData) {
        //     messages.innerHTML = messages.innerHTML + `<p class="my-2 mx-2 bg-white rounded-xl">${messageData['username']} : ${messageData['message']}</p>`
        // }
        function addMessage(messageData) {
            messages.innerHTML = messages.innerHTML + `<div class="flex mt-2">
            <p class="text-sm font-semibold mr-2 mt-2">${messageData['username']} : </p>
            <p class="bg-white rounded-xl p-2">${messageData['message']}</p>
        </div>`

        scrollToBottom();
        }

        // Event handler for receiving messages
        ws.onmessage = function(event) {
            console.log('Message received:', event.data);
            messageData = JSON.parse(event.data)
            addMessage(messageData);


        };

        

        const chatInput = document.getElementById("chat-message");
        const sendButton = document.getElementById("send-button");

        sendButton.addEventListener('click', function(event) {
            console.log("button clicked");
            event.preventDefault();
            const data = {
                'message': chatInput.value,
                'username': userName
            };
            const jsonData = JSON.stringify(data);
            ws.send(jsonData);
            chatInput.value = '';
            scrollToBottom();
        });
    }

    function scrollToBottom() {
        let objDiv = document.getElementById("show-messages");
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    // Add this below the function to trigger the scroll on load.
    scrollToBottom();
    </script>
{% endblock script %}

room/templates/room/chat_rooms.html
{% extends "core/base.html" %}

{% block content %}
<h1 class="text-yellow-800 text-4xl font-bold mb-10">
    Chat Rooms
</h1>



<a href="{% url 'room:create-room' %}" class="font-bold text-white text-xl mb-40 bg-yellow-400 rounded-xl p-3">Create Room</a>

<div class="mx-2 my-2 mt-10">
    {% for room in rooms %}
    <div class="flex items-center justify-between bg-white rounded-xl p-4 mb-4">
        <h3 class="text-lg font-semibold">{{ room.name }}</h3>
        <a href="{% url 'room:chat-room' room.slug %}" class="px-4 py-2 bg-yellow-400 text-white rounded-md hover:bg-yellow-600">Join Room</a>
    </div>
    {% endfor %}
</div>

<!-- <div class="mx-2 my-2">
    {% for room in rooms %}
    <h3>{{room.name}}</h3>
    <a href="{% url 'room:chat-room' room.slug %}">Join Room</a>
    {% endfor %}

</div> -->
{% endblock %}

room/templates/room/create_room.html
{% extends "core/base.html" %}

{% block content %}
<div>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Room</button>
    </form>
</div>
{% endblock content %}